# Generated by Django 5.0.2 on 2025-05-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='age',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
