# Generated by Django 5.0.2 on 2025-05-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadapp', '0002_contactenquiry_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdfData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectPdf', models.TextField()),
                ('fullName', models.CharField(max_length=50)),
                ('estimateNum', models.IntegerField()),
                ('currentDate', models.DateField()),
                ('placeField', models.CharField(max_length=50)),
            ],
        ),
    ]
